### ISSUE TITLE
fix Stripe subscriptions deploy mode

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/drewapp#49]
- click subscribe -> error
<img width="300" alt="Screenshot 2024-10-20 at 8 24 29 PM" src="https://github.com/user-attachments/assets/2dd41f2e-b276-4d6c-b4c4-4d972fcee43b">

### TODO
- [x] check logs
  - [x] ~~add S_S_K~~
  - [x] try access credentials in cloned repo
  - [x] credentials.ymc.enc, 353b98d
- [x] check logs
  - [x] add `webhook_signing_secret` to prod credentials
- [x] add stripe webhooks endpoint in dashboard

### Screenshots
<img width="300" alt="Screenshot 2024-10-20 at 9 20 49 PM" src="https://github.com/user-attachments/assets/6043fae0-0f69-4814-8b8a-21517820d27b">

### Manual test
- user checks out, success page, but I think webhook not on as no subscribed alert; check database

**Comment by adnjoo** [comment]
> Stripe api keys are working fine in development, I have set the stripe live api keys in env variables, but still facing the issue mentioned in subject on deployment.


https://community.render.com/t/stripe-authenticationerror-no-api-key-provided/14065
